import {
  PrismaClient,
  WorkoutStatus,
  AuthProvider,
  PlanType,
} from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Démarrage du seed Prisma pour Riles Backend...");

  // Nettoyage complet des données précédentes
  await prisma.webhookEvent.deleteMany({});
  await prisma.rpeCheckIn.deleteMany({});
  await prisma.chatMessage.deleteMany({});
  await prisma.quickPrompt.deleteMany({});
  await prisma.syncToken.deleteMany({});
  await prisma.lifeRule.deleteMany({});
  await prisma.workout.deleteMany({});
  await prisma.user.deleteMany({});

  // 1. Profil Utilisateur Réaliste (Marius)
  const user = await prisma.user.create({
    data: {
      id: "user-01",
      email: "marius@riles.app",
      name: "Marius",
      initials: "ML",
      readinessScore: 88,
      activeGoalTitle: "Semi-marathon de Paris",
      activeGoalTarget: "Passer sous les 2h",
      activeGoalRaceDate: "17 mars 2025",
      activeGoalWeeksRemaining: 6,
      activeGoalProgressPercentage: 65,
      activeWeeks: 12,
      totalKm: 328.0,
      completedRaces: 4,
      planType: PlanType.PRO,
      authProvider: AuthProvider.APPLE,
      isOnboardingCompleted: true,
      mainGoal: "Me préparer pour mon premier semi-marathon sans me blesser",
      selectedSports: ["running"],
    },
  });

  console.log(
    `👤 Utilisateur créé : ${user.name} (${user.email}) - Score de forme : ${user.readinessScore}%`,
  );

  // 2. Règles de vie & Préférences (Jours verrouillés, créneaux, philosophie)
  await prisma.lifeRule.createMany({
    data: [
      {
        userId: user.id,
        title: "Jours verrouillés",
        description:
          "Pas d'entraînement le jeudi (famille et récupération active).",
        icon: "calendar-lock",
      },
      {
        userId: user.id,
        title: "Créneaux préférés",
        description: "En semaine à 18h30 après le travail, le samedi à 09h00.",
        icon: "clock-outline",
      },
      {
        userId: user.id,
        title: "Constance & Plaisir",
        description:
          "La régularité avant l'intensité pour préserver les mollets.",
        icon: "bullseye-arrow",
      },
      {
        userId: user.id,
        title: "Sommeil & Récupération",
        description: "Minimum 7h30 de sommeil avant les sorties de seuil.",
        icon: "sleep",
      },
    ],
  });

  console.log("🛡️ Règles de vie & contraintes enregistrées");

  // 3. Jetons de synchronisation Sport & Santé (Strava, Garmin, Apple Health)
  await prisma.syncToken.createMany({
    data: [
      {
        userId: user.id,
        provider: "garmin",
        isConnected: true,
        externalUserId: "garmin_usr_marius_8841",
        accessToken: "mock_garmin_access_token_sec_2026",
        refreshToken: "mock_garmin_refresh_token_sec_2026",
        metadata: {
          deviceName: "Garmin Forerunner 265",
          lastSyncAt: new Date().toISOString(),
          batteryLevel: 84,
        },
      },
      {
        userId: user.id,
        provider: "strava",
        isConnected: true,
        externalUserId: "strava_athlete_942187",
        accessToken: "mock_strava_access_token_sec_2026",
        refreshToken: "mock_strava_refresh_token_sec_2026",
        metadata: {
          athleteName: "Marius L.",
          premium: true,
          lastActivitySynced: "Footing Fondamental Léger (7 km)",
        },
      },
      {
        userId: user.id,
        provider: "apple_health",
        isConnected: false,
        metadata: {
          availableMetrics: [
            "heart_rate",
            "vo2max",
            "resting_hr",
            "sleep_analysis",
          ],
        },
      },
    ],
  });

  console.log("⌚ Jetons de synchronisation sport-santé configurés");

  // 4. Suggestions rapides (Quick Prompts)
  await prisma.quickPrompt.createMany({
    data: [
      {
        id: "qp-1",
        label: "Je suis fatigué ce soir",
        message:
          "Je me sens très fatigué après ma journée de travail, dois-je maintenir ma séance de seuil ?",
        order: 1,
      },
      {
        id: "qp-2",
        label: "Décaler à demain",
        message:
          "J’ai un imprévu ce soir, peux-tu décaler la séance à demain sans déséquilibrer ma semaine ?",
        order: 2,
      },
      {
        id: "qp-3",
        label: "Footing cool 30 min",
        message:
          "Je préfère faire 30 min de footing souple à la place, peux-tu ajuster mon plan ?",
        order: 3,
      },
      {
        id: "qp-4",
        label: "Gêne au mollet",
        message:
          "J’ai ressenti une petite gêne au mollet hier, quelle précaution prendre aujourd’hui ?",
        order: 4,
      },
    ],
  });

  // 5. Historique du chat avec le Coach IA
  await prisma.chatMessage.createMany({
    data: [
      {
        userId: user.id,
        sender: "coach",
        text: "Bonjour Marius ! Je suis ton Coach IA Riles. Ton score de préparation est excellent aujourd'hui (88%). Prêt pour ta sortie seuil ?",
        timestamp: "18:15",
      },
      {
        userId: user.id,
        sender: "user",
        text: "J’ai une légère tension au mollet gauche suite à la sortie de mardi.",
        timestamp: "18:18",
      },
      {
        userId: user.id,
        sender: "coach",
        text: "Prudence avant tout ! Une gêne au mollet peut vite évoluer en contracture. Je te propose d'alléger la séance de ce soir pour sécuriser ta préparation sans risque de blessure.",
        timestamp: "18:19",
        suggestedAction: {
          type: "reduce_intensity",
          label: "Appliquer : Alléger la séance à 35 min",
          applied: false,
          details: "lighten",
        },
      },
    ],
  });

  // 6. Plan d'entraînement complet (Semaines 40, 41, 42 et 43 - Mois d'Octobre 2026)
  const workoutsData = [
    // ================= SEMAINE 40 =================
    {
      userId: user.id,
      dateKey: "2026-09-28",
      dayName: "Lun",
      dayNumber: 28,
      month: 8,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "LUNDI 28 SEPTEMBRE",
      timeLabel: "18:00",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "REPRISE & AISANCE",
      title: "Footing Reprise & Décrassage",
      duration: "40 min",
      distance: "6,5 km",
      targetPace: "5:50/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "130–145 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 3 },
        { color: "#34D399", flex: 3 },
      ],
      pinPositionPercent: 30,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Endurance",
          durationLabel: "25 min",
          type: "interval",
          flexRatio: 3,
        },
        {
          title: "Retour au calme",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["6,5 km", "Allure : 5:50/km", "Zone 2"],
      aiAdjustmentNote:
        "Reprise progressive validée avec aisance respiratoire.",
    },
    {
      userId: user.id,
      dateKey: "2026-09-29",
      dayName: "Mar",
      dayNumber: 29,
      month: 8,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "MARDI 29 SEPTEMBRE",
      timeLabel: "18:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "RENFORCEMENT & MOBILITÉ",
      title: "Renforcement Musculaire & Core",
      duration: "35 min",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "110–130 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 4 }],
      pinPositionPercent: 20,
      effortBlocks: [
        {
          title: "Mobilité",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Circuit Gainage",
          durationLabel: "20 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Étirements",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["35 min", "Core & fessiers", "Zone 1"],
      aiAdjustmentNote:
        "Bonne exécution des exercices de renforcement du bassin.",
    },
    {
      userId: user.id,
      dateKey: "2026-09-30",
      dayName: "Mer",
      dayNumber: 30,
      month: 8,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "MERCREDI 30 SEPTEMBRE",
      timeLabel: "18:15",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "SÉANCE QUALITATIVE",
      title: "Footing Progressif & Lignes Droites",
      duration: "45 min",
      distance: "7,8 km",
      targetPace: "5:30/km",
      targetZoneLabel: "Zone 2–3",
      targetZoneBpm: "140–155 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 2 },
        { color: "#34D399", flex: 3 },
        { color: "#FBBF24", flex: 1 },
      ],
      pinPositionPercent: 45,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "15 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Accélérations",
          durationLabel: "25 min",
          type: "interval",
          flexRatio: 2,
        },
        {
          title: "Retour au calme",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["7,8 km", "Allure : 5:30/km", "Zone 2/3"],
      aiAdjustmentNote:
        "Excellente progression dans le rythme sans dérive cardiaque.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-01",
      dayName: "Jeu",
      dayNumber: 1,
      month: 9,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "JEUDI 1 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "RÉCUPÉRATION PASSIVE",
      title: "Repos complet & Hydratation",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Hydratation", "Repos"],
      aiAdjustmentNote: "Assimilation du bloc de début de semaine.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-02",
      dayName: "Ven",
      dayNumber: 2,
      month: 9,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "VENDREDI 2 OCTOBRE",
      timeLabel: "12:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "ALLURE SPÉCIFIQUE",
      title: "Allure Spécifique Semi 4 × 1000m",
      duration: "50 min",
      distance: "9,0 km",
      targetPace: "4:55/km",
      targetZoneLabel: "Zone 3–4",
      targetZoneBpm: "160–174 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1 },
        { color: "#FBBF24", flex: 2 },
        { color: "#FC4C02", flex: 2 },
      ],
      pinPositionPercent: 70,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "15 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "4 × 1000m",
          durationLabel: "25 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["9,0 km", "Allure cible : 4:55/km", "Zone 4"],
      aiAdjustmentNote:
        "Allure semi maîtrisée avec régularité sur chaque fraction.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-03",
      dayName: "Sam",
      dayNumber: 3,
      month: 9,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "SAMEDI 3 OCTOBRE",
      timeLabel: "09:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "VOLUME & ENDURANCE",
      title: "Sortie Aérobie Douce",
      duration: "1h10",
      distance: "12,0 km",
      targetPace: "5:40/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "135–150 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 2 },
        { color: "#34D399", flex: 3 },
      ],
      pinPositionPercent: 40,
      effortBlocks: [
        {
          title: "Endurance de base",
          durationLabel: "60 min",
          type: "interval",
          flexRatio: 4,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["12,0 km", "Aérobie", "Zone 2"],
      aiAdjustmentNote:
        "Très bon volume aérobie pour clore la première semaine d'octobre.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-04",
      dayName: "Dim",
      dayNumber: 4,
      month: 9,
      year: 2026,
      weekNumber: 40,
      fullDateLabel: "DIMANCHE 4 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "BILAN DE SEMAINE",
      title: "Repos & Étirements Doux",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Bilan hebdo", "Récupération"],
      aiAdjustmentNote: "Total semaine validé : 35,3 km.",
    },

    // ================= SEMAINE 41 =================
    {
      userId: user.id,
      dateKey: "2026-10-05",
      dayName: "Lun",
      dayNumber: 5,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "LUNDI 5 OCTOBRE",
      timeLabel: "18:00",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "AÉROBIE & DÉVELOPPEMENT",
      title: "Footing Aérobie 45 min",
      duration: "45 min",
      distance: "8,0 km",
      targetPace: "5:35/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "135–148 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 3 },
        { color: "#34D399", flex: 4 },
      ],
      pinPositionPercent: 35,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Footing aérobie",
          durationLabel: "30 min",
          type: "interval",
          flexRatio: 3,
        },
        {
          title: "Retour au calme",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["8,0 km", "Allure : 5:35/km", "Zone 2"],
      aiAdjustmentNote: "Bonne constance cardiaque sur sol plat.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-06",
      dayName: "Mar",
      dayNumber: 6,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "MARDI 6 OCTOBRE",
      timeLabel: "18:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "RENFORCEMENT & MOBILITÉ",
      title: "Renforcement Posture & Mollets",
      duration: "35 min",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "115–130 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 3 }],
      pinPositionPercent: 20,
      effortBlocks: [
        {
          title: "Mobilité articulaire",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Excentrique mollets",
          durationLabel: "20 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Étirements légers",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["35 min", "Prévention blessure", "Zone 1"],
      aiAdjustmentNote:
        "Travail excentrique bien dosé pour renforcer le tendon d'Achille.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-07",
      dayName: "Mer",
      dayNumber: 7,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "MERCREDI 7 OCTOBRE",
      timeLabel: "18:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "SÉANCE QUALITATIVE",
      title: "Pyramide au Seuil (2-3-4-3-2 min)",
      duration: "55 min",
      distance: "10,2 km",
      targetPace: "4:45/km",
      targetZoneLabel: "Zone 3–4",
      targetZoneBpm: "162–175 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1.5 },
        { color: "#FBBF24", flex: 2 },
        { color: "#FC4C02", flex: 2 },
      ],
      pinPositionPercent: 72,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "15 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Fractions Pyramide",
          durationLabel: "30 min",
          type: "threshold",
          flexRatio: 3,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["10,2 km", "Seuil pyramidal", "Zone 4"],
      aiAdjustmentNote:
        "Très bon engagement, allures tenues sur les blocs de 4 min.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-08",
      dayName: "Jeu",
      dayNumber: 8,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "JEUDI 8 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "RÉCUPÉRATION PASSIVE",
      title: "Repos complet & Récupération",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Jour verrouillé", "Hydratation"],
      aiAdjustmentNote: "Respect du jour de repos programmé.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-09",
      dayName: "Ven",
      dayNumber: 9,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "VENDREDI 9 OCTOBRE",
      timeLabel: "12:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "ENDURANCE ACTIVE",
      title: "Footing Aisance & Lignes Droites",
      duration: "40 min",
      distance: "7,2 km",
      targetPace: "5:30/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "132–146 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 3 },
        { color: "#34D399", flex: 3 },
      ],
      pinPositionPercent: 35,
      effortBlocks: [
        {
          title: "Endurance",
          durationLabel: "35 min",
          type: "interval",
          flexRatio: 3,
        },
        {
          title: "5 lignes droites",
          durationLabel: "5 min",
          type: "threshold",
          flexRatio: 1,
        },
      ],
      tags: ["7,2 km", "Lignes droites", "Zone 2"],
      aiAdjustmentNote: "Dynamisme retrouvé en fin de séance.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-10",
      dayName: "Sam",
      dayNumber: 10,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "SAMEDI 10 OCTOBRE",
      timeLabel: "09:00",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "SORTIE LONGUE",
      title: "Sortie Longue 1h25 (15 km)",
      duration: "1h25",
      distance: "15,0 km",
      targetPace: "5:35/km",
      targetZoneLabel: "Zone 2–3",
      targetZoneBpm: "136–152 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 2 },
        { color: "#34D399", flex: 4 },
        { color: "#FBBF24", flex: 1 },
      ],
      pinPositionPercent: 50,
      effortBlocks: [
        {
          title: "Endurance fondamentale",
          durationLabel: "65 min",
          type: "warmup",
          flexRatio: 4,
        },
        {
          title: "Allure cible fin",
          durationLabel: "15 min",
          type: "threshold",
          flexRatio: 1,
        },
        {
          title: "Retour au calme",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["15,0 km", "Volume clé", "Zone 2/3"],
      aiAdjustmentNote: "Validation de la tenue énergétique sur 15 km.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-11",
      dayName: "Dim",
      dayNumber: 11,
      month: 9,
      year: 2026,
      weekNumber: 41,
      fullDateLabel: "DIMANCHE 11 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "BILAN DE SEMAINE",
      title: "Repos & Régénération",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Bilan hebdo", "Sommeil"],
      aiAdjustmentNote: "Semaine 41 clôturée à 40,4 km.",
    },

    // ================= SEMAINE 42 (SEMAINE ACTIVE) =================
    {
      userId: user.id,
      dateKey: "2026-10-12",
      dayName: "Lun",
      dayNumber: 12,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "LUNDI 12 OCTOBRE",
      timeLabel: "18:00",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "RÉCUPÉRATION ACTIVE",
      title: "Footing Fondamental Léger",
      duration: "40 min",
      distance: "7,0 km",
      targetPace: "5:45/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "130–145 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 3 },
        { color: "#34D399", flex: 4 },
        { color: "#FBBF24", flex: 1 },
      ],
      pinPositionPercent: 35,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Footing souple",
          durationLabel: "25 min",
          type: "interval",
          flexRatio: 3,
        },
        {
          title: "Retour au calme",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["7,0 km", "Allure : 5:45/km", "Zone 2"],
      aiAdjustmentNote:
        "Séance réalisée avec une régularité cardiaque parfaite.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-13",
      dayName: "Mar",
      dayNumber: 13,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "MARDI 13 OCTOBRE",
      timeLabel: "18:30",
      status: WorkoutStatus.DONE,
      isRestDay: false,
      category: "RENFORCEMENT & MOBILITÉ",
      title: "Gainage & Travail de Pied",
      duration: "35 min",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1–2",
      targetZoneBpm: "110–135 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 4 },
        { color: "#34D399", flex: 2 },
      ],
      pinPositionPercent: 25,
      effortBlocks: [
        {
          title: "Mobilité chevilles",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Circuit gainage",
          durationLabel: "20 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Étirements",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["35 min", "Corps complet", "Zone 1"],
      aiAdjustmentNote:
        "Indispensable pour stabiliser la posture sur le semi-marathon.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-14",
      dayName: "Mer",
      dayNumber: 14,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "MERCREDI 14 OCTOBRE",
      timeLabel: "AUJOURD'HUI • 18:30",
      status: WorkoutStatus.SELECTED,
      isRestDay: false,
      category: "SÉANCE QUALITATIVE",
      title: "Sortie Seuil & Allure Cible",
      duration: "1h15",
      distance: "14 km",
      targetPace: "4:50/km",
      targetZoneLabel: "Zone 3–4",
      targetZoneBpm: "158–172 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1.2 },
        { color: "#FBBF24", flex: 2 },
        { color: "#FC4C02", flex: 2 },
      ],
      pinPositionPercent: 68,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "15 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Seuil",
          durationLabel: "3 × 8 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["8,5 km", "Allure cible : 4:45/km", "Zone 3/4"],
      aiAdjustmentNote:
        "L'IA a ajusté le seuil pour préserver tes mollets aujourd'hui.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-15",
      dayName: "Jeu",
      dayNumber: 15,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "JEUDI 15 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "RÉCUPÉRATION PASSIVE",
      title: "Repos complet ou marche",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Récupération", "Hydratation"],
      aiAdjustmentNote: "Assimilation de la séance de seuil de mercredi.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-16",
      dayName: "Ven",
      dayNumber: 16,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "VENDREDI 16 OCTOBRE",
      timeLabel: "12:30",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "ALLURE CIBLE",
      title: "Rappels Allure Spécifique 3 × 1500m",
      duration: "50 min",
      distance: "8,5 km",
      targetPace: "4:55/km",
      targetZoneLabel: "Zone 3–4",
      targetZoneBpm: "160–172 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1 },
        { color: "#FBBF24", flex: 2 },
        { color: "#FC4C02", flex: 2 },
      ],
      pinPositionPercent: 65,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "15 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "3 × 1500m",
          durationLabel: "25 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["8,5 km", "Allure semi", "Zone 3/4"],
      aiAdjustmentNote: "Validation de l'économie de course à vitesse cible.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-17",
      dayName: "Sam",
      dayNumber: 17,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "SAMEDI 17 OCTOBRE",
      timeLabel: "09:00",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "SORTIE LONGUE",
      title: "Sortie Longue Progressive 1h35",
      duration: "1h35",
      distance: "17,5 km",
      targetPace: "5:25/km",
      targetZoneLabel: "Zone 2–3",
      targetZoneBpm: "138–156 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1 },
        { color: "#34D399", flex: 3 },
        { color: "#FBBF24", flex: 2 },
      ],
      pinPositionPercent: 55,
      effortBlocks: [
        {
          title: "Endurance",
          durationLabel: "60 min",
          type: "warmup",
          flexRatio: 3,
        },
        {
          title: "Tempo fin de sortie",
          durationLabel: "25 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["17,5 km", "Progressif", "Zone 2/3"],
      aiAdjustmentNote:
        "Séance pilier de la préparation pour tester le ravitaillement.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-18",
      dayName: "Dim",
      dayNumber: 18,
      month: 9,
      year: 2026,
      weekNumber: 42,
      fullDateLabel: "DIMANCHE 18 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "BILAN DE SEMAINE",
      title: "Repos & Régénération Totale",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Bilan hebdo", "Sommeil"],
      aiAdjustmentNote: "Clôture de la semaine 42. Objectif estimé : 47 km.",
    },

    // ================= SEMAINE 43 =================
    {
      userId: user.id,
      dateKey: "2026-10-19",
      dayName: "Lun",
      dayNumber: 19,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "LUNDI 19 OCTOBRE",
      timeLabel: "18:00",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "RÉCUPÉRATION ACTIVE",
      title: "Footing Doux & Décrassage",
      duration: "40 min",
      distance: "6,8 km",
      targetPace: "5:50/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "130–145 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 3 },
        { color: "#34D399", flex: 3 },
      ],
      pinPositionPercent: 30,
      effortBlocks: [
        {
          title: "Footing souple",
          durationLabel: "35 min",
          type: "interval",
          flexRatio: 3,
        },
        {
          title: "Retour au calme",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["6,8 km", "Aisance", "Zone 2"],
      aiAdjustmentNote: "Reprise post-sortie longue du weekend.",
    },
    {
      userId: user.id,
      dateKey: "2026-10-20",
      dayName: "Mar",
      dayNumber: 20,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "MARDI 20 OCTOBRE",
      timeLabel: "18:30",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "RENFORCEMENT & MOBILITÉ",
      title: "Gainage Fonctionnel & Posture",
      duration: "35 min",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "110–130 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 4 }],
      pinPositionPercent: 20,
      effortBlocks: [
        {
          title: "Mobilité",
          durationLabel: "10 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "Gainage",
          durationLabel: "20 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Étirements",
          durationLabel: "5 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["35 min", "Renforcement", "Zone 1"],
    },
    {
      userId: user.id,
      dateKey: "2026-10-21",
      dayName: "Mer",
      dayNumber: 21,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "MERCREDI 21 OCTOBRE",
      timeLabel: "18:30",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "SÉANCE QUALITATIVE",
      title: "Seuil Long 2 × 3000m",
      duration: "1h05",
      distance: "12,5 km",
      targetPace: "4:50/km",
      targetZoneLabel: "Zone 3–4",
      targetZoneBpm: "160–174 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1.5 },
        { color: "#FBBF24", flex: 2 },
        { color: "#FC4C02", flex: 2 },
      ],
      pinPositionPercent: 70,
      effortBlocks: [
        {
          title: "Échauffement",
          durationLabel: "15 min",
          type: "warmup",
          flexRatio: 1,
        },
        {
          title: "2 × 3000m",
          durationLabel: "35 min",
          type: "threshold",
          flexRatio: 3,
        },
        {
          title: "Retour au calme",
          durationLabel: "15 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["12,5 km", "Seuil 3000m", "Zone 4"],
    },
    {
      userId: user.id,
      dateKey: "2026-10-22",
      dayName: "Jeu",
      dayNumber: 22,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "JEUDI 22 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "RÉCUPÉRATION PASSIVE",
      title: "Repos & Hydratation",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Jour verrouillé", "Hydratation"],
    },
    {
      userId: user.id,
      dateKey: "2026-10-23",
      dayName: "Ven",
      dayNumber: 23,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "VENDREDI 23 OCTOBRE",
      timeLabel: "12:30",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "AÉROBIE",
      title: "Footing Aisance & Déblocage",
      duration: "45 min",
      distance: "8,0 km",
      targetPace: "5:35/km",
      targetZoneLabel: "Zone 2",
      targetZoneBpm: "135–148 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 3 },
        { color: "#34D399", flex: 4 },
      ],
      pinPositionPercent: 35,
      effortBlocks: [
        {
          title: "Endurance",
          durationLabel: "40 min",
          type: "interval",
          flexRatio: 4,
        },
        {
          title: "Lignes droites",
          durationLabel: "5 min",
          type: "threshold",
          flexRatio: 1,
        },
      ],
      tags: ["8,0 km", "Aisance", "Zone 2"],
    },
    {
      userId: user.id,
      dateKey: "2026-10-24",
      dayName: "Sam",
      dayNumber: 24,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "SAMEDI 24 OCTOBRE",
      timeLabel: "09:00",
      status: WorkoutStatus.UPCOMING,
      isRestDay: false,
      category: "SORTIE LONGUE",
      title: "Sortie Longue 1h45 (19 km)",
      duration: "1h45",
      distance: "19,0 km",
      targetPace: "5:30/km",
      targetZoneLabel: "Zone 2–3",
      targetZoneBpm: "138–155 bpm",
      targetZoneSegments: [
        { color: "#93C5FD", flex: 1.5 },
        { color: "#34D399", flex: 3.5 },
        { color: "#FBBF24", flex: 2 },
      ],
      pinPositionPercent: 55,
      effortBlocks: [
        {
          title: "Endurance fondamentale",
          durationLabel: "75 min",
          type: "warmup",
          flexRatio: 4,
        },
        {
          title: "Bloc Allure Semi",
          durationLabel: "20 min",
          type: "threshold",
          flexRatio: 2,
        },
        {
          title: "Retour au calme",
          durationLabel: "10 min",
          type: "cooldown",
          flexRatio: 1,
        },
      ],
      tags: ["19,0 km", "Pic de volume", "Zone 2/3"],
    },
    {
      userId: user.id,
      dateKey: "2026-10-25",
      dayName: "Dim",
      dayNumber: 25,
      month: 9,
      year: 2026,
      weekNumber: 43,
      fullDateLabel: "DIMANCHE 25 OCTOBRE",
      timeLabel: "Jour de repos",
      status: WorkoutStatus.REST,
      isRestDay: true,
      category: "BILAN DE SEMAINE",
      title: "Repos & Récupération Complète",
      duration: "—",
      distance: "0 km",
      targetPace: "—",
      targetZoneLabel: "Zone 1",
      targetZoneBpm: "< 110 bpm",
      targetZoneSegments: [{ color: "#93C5FD", flex: 1 }],
      pinPositionPercent: 10,
      effortBlocks: [
        {
          title: "Repos",
          durationLabel: "Toute la journée",
          type: "recovery",
          flexRatio: 1,
        },
      ],
      tags: ["Bilan hebdo", "Récupération"],
    },
  ];

  let createdWorkoutCount = 0;
  let createdWorkoutsList = [];
  for (const item of workoutsData) {
    const w = await prisma.workout.create({
      data: item,
    });
    createdWorkoutsList.push(w);
    createdWorkoutCount++;
  }

  console.log(
    `🏃 ${createdWorkoutCount} séances d'entraînement insérées dans le calendrier`,
  );

  // 7. Check-ins RPE initiaux
  const mondaySession = createdWorkoutsList.find(
    (w) => w.dateKey === "2026-10-12",
  );
  const wednesdaySession = createdWorkoutsList.find(
    (w) => w.dateKey === "2026-10-14",
  );

  if (mondaySession) {
    await prisma.rpeCheckIn.create({
      data: {
        userId: user.id,
        workoutId: mondaySession.id,
        rating: 4,
        feedbackLabel: "Facile",
        aiPreservationMessage:
          "Séance aérobie bien assimilée. Niveau de récupération optimal.",
        submittedAt: new Date("2026-10-12T19:00:00.000Z"),
      },
    });
  }

  await prisma.rpeCheckIn.create({
    data: {
      userId: user.id,
      workoutId: wednesdaySession?.id,
      rating: 5,
      feedbackLabel: "Modéré",
      aiPreservationMessage:
        "L'IA a ajusté le seuil pour préserver tes mollets aujourd'hui.",
      submittedAt: new Date("2026-10-14T18:35:00.000Z"),
    },
  });

  console.log("📊 Check-ins RPE et feedbacks d'effort enregistrés");
  console.log("✅ Seed Prisma exécuté avec succès pour Riles !");
}

main()
  .catch((e) => {
    console.error("❌ Erreur pendant le seed :", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
